# Generated by Django 5.0.3 on 2024-04-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
