# Generated by Django 5.0.3 on 2024-04-01 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0004_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_plate', message='Invalid license plate format.', regex='^[A-Z0-9]+(?:[- ][A-Z0-9]+)?$')]),
        ),
    ]
