# Generated by Django 5.0.3 on 2024-04-02 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0005_alter_bus_options_alter_bus_registration_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_service',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
