# Generated by Django 5.0.3 on 2024-04-02 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0006_bus_last_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='last_service',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
