# Generated by Django 5.0.3 on 2024-04-02 22:23

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0007_alter_bus_last_service'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('admin', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
